### PR TITLE
don't generate a new key in ecSign

### PR DESCRIPTION
**Pull request by mvayngrib**

### CODE REVIEW

**Comment by jprichardson** [comment]
utACK

**Comment by dcousens** [comment]
Thanks @mvayngrib :+1:

**Comment by calvinmetcalf** [comment]
does this require a specific version of elliptic ?

**Comment by mvayngrib** [comment]
the explicit key import methods were added just before 2.0.0

https://github.com/indutny/elliptic/commit/b6ff1758d9a6d1a7aec177ff6df9f586492a6315

screen shot 2016-09-13 at 8 57 11 am

**Comment by calvinmetcalf** [comment]
well then that works well

**Pull request merged**
