### PR TITLE
correct error message

### PR DESCRIPTION
**Pull request by calvinmetcalf**
we we're throwing an error about public keys when we needed a private key

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
though node makes the same mistake

**Comment by dcousens** [comment]
> though node makes the same mistake

What about iojs?

**Comment by calvinmetcalf** [comment]
It was iojs I was testing against

**Comment by dcousens** [comment]
@calvinmetcalf can you make a PR upstream?

**Comment by calvinmetcalf** [comment]
maybe depends if it's an issue in node/iojs (in which case yes) or one in
opnessl (in which case no)

**Comment by dcousens** [comment]
Maybe they were the same, because in the end, both error messages would technically be correct?

**Comment by calvinmetcalf** [comment]
it is a technically correct error message because it is an issue with the public key cryptosystem type, but since it uses the phrase public key by it's self when you are actually give it an incorrect private key means it implies the issues is with the public key file.  Confused me to no end while I was debugging and issue that ended up being caused by passing an rsa key to something that wanted an EC one.

**Comment by dcousens** [comment]
Maybe before we publish this, you should establish if this is actually
consistent with iojs.  I know it sucks, but, people will rely on this being
consistent.

**Comment by calvinmetcalf** [comment]
this is not consistent with iojs when I said node in the second comment I meant iojs (which I was testing against)

**Comment by dcousens** [comment]
@dominictarr thoughts?

**Comment by dominictarr** [comment]
If we have to choose we should be consistent with iojs. If there is a problem with iojs I am confidant we can fix it... and eventually that might get into joyent/node

**Comment by calvinmetcalf** [comment]
so the issue stems from [here](https://github.com/iojs/io.js/blob/a84ea66b35cce2e44fa35699a2a09194b0a5210c/deps/openssl/openssl/crypto/evp/p_sign.c#L123) so more or an openssl thing then a node thing

**Pull request merged**
