### PR TITLE
Fixes unreachable return error

### PR DESCRIPTION
**Pull request by psychobunny**
Latest FF throws a syntax error here, also I'm assuming you did want to check the signType anyways :)

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
let me fix the tests before we merge this, it's throwing syntax errors for files you didn't change

**Comment by dcousens** [comment]
utACK

**Comment by psychobunny** [comment]
Okay, cool. We are switching [NodeBB](https://github.com/NodeBB/NodeBB) from require.js to browserify so this is currently blocking. That said, no rush, looking forward to getting this merged though! :)

**Comment by psychobunny** [comment]
:+1:

**Comment by dcousens** [comment]
Its easier to merge this than fix the errors, simply because this was actually already caught by https://github.com/feross/standard

**Comment by dcousens** [comment]
Fixing the other errors in a new PR.

**Comment by calvinmetcalf** [comment]
and published should be all set now

**Pull request merged**
