### PR TITLE
update dependencies, adds/fixes failing test for auth0/node-jsonwebtoken#91

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
looks to be 2 issues

- reverting bn to version 1.1 causes the only issue to be that we can't verify the signature
- when bn is 1.2 or 1.3 we also generate them badly

**Comment by calvinmetcalf** [comment]
and bn is now up to version 2, but upgrading requires us to upgrade elliptic which has  a breaking api change

**Comment by dcousens** [comment]
Any idea what is causing the bug?  Also, where is the test data from?

**Comment by calvinmetcalf** [comment]
yeah it's a bug in BN.js, the test data was from the script in the linked
issue, I ran it until it failed and then saved the data that caused it to
crash consistently

**Comment by dcousens** [comment]
@calvinmetcalf have you submitted the bug to bn.js?

**Comment by calvinmetcalf** [comment]
Out of date version of bn.js only, fix is to upgrade

**Comment by dcousens** [comment]
@calvinmetcalf what remains to be upgraded?  Or is this PR now good to merge?

**Comment by calvinmetcalf** [comment]
Half of this bug is fixed in browserify-rsa, mainly I'd like to get all of
the pulls to upgrade bn and elliptic merged before I publish so we can
minimize the amount of time we get conflicting versions duplicated.

There is also new major version of asn1.js out or about to get out, it just
consistently returns big numbers for all integers instead of sometimes
giving regular numbers, this shouldn't affect us as I don't think I ever
assume i am given a big number in code.

I can check on that and what other pulls are left when I get into the
office (on the train now)

**Comment by calvinmetcalf** [comment]
https://github.com/pulls?user=crypto-browserify is the master list of pulls, crypto-browserify/browserify-rsa#3 still needs to be merged

**Comment by calvinmetcalf** [comment]
todo:

- [ ] publish browserify-rsa
- [ ] merge this
- [ ] publish this
- [ ] publish parseasn1
- [ ] publish publicEncrypt
- [ ] publish createECDH
- [ ] publish diffie-hellmen

**Comment by calvinmetcalf** [comment]
we probably want to wait until 2 of us are awake at the same time before doing this so we can merge and publish this quickly after publishing browserify-rsa (or if that doesn't work rolling back browserify-rsa)

**Comment by dcousens** [comment]
@calvinmetcalf do you have slack?

**Comment by calvinmetcalf** [comment]
some, I mainly use irc

**Pull request merged**
