### PR TITLE
more ecdsa

### PR DESCRIPTION
**Pull request by calvinmetcalf**
should solve #28, needs tests

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
[this](https://gist.github.com/calvinmetcalf/73b6438bffed37c8c163ec31d656911d) is what I used to generate the new fixtures

**Comment by samuelhorwitz** [comment]
Were there any shortcomings with this? I manually patched on my end and it seems fine and also fixes a bug I'm having with a JWS library used in Node (that I downstream patched in tandem) https://github.com/brianloveswords/node-jwa/issues/8

Basically, that guy uses some tricks to end up in OpenSSL where ECDSA will be handled correctly, but those tricks don't work in browser obviously. However with the patch here, and a patch over there, I can get that library to work with this one

**Comment by dcousens** [comment]
Have not verified with external software,  but the fixtures look good. 

@calvinmetcalf any easy way to compare these?

**Comment by samuelhorwitz** [comment]
Thanks!

**Pull request merged**
