### PR TITLE
Add LICENSE file.

### PR DESCRIPTION
**Pull request by mkillianey**
I've added the ISC license.  (Not sure whether or not this was intentionally licensed as ISC instead of MIT, like some of the other crypto-browserify packages...please let me know if this isn't what you wanted.)

### CODE REVIEW

**Comment by dcousens** [comment]
Granted the main contributor is @calvinmetcalf,  I'd prefer if it said:

> Copyright (c) 2015 The contributors

or something

**Comment by calvinmetcalf** [comment]
A couple things

- I've privatized myself and no longer work for the state so I know use a Gmail account primarily. 
- we probably want at least one name in the licence.

**Comment by dcousens** [comment]
> we probably want at least one name in the licence.

Any reason?

**Comment by calvinmetcalf** [comment]
So there is somebody that a person can email or contact or something I
figure it can't hurt.

**Comment by dcousens** [comment]
@calvinmetcalf maybe put that in a contributor list item then?
It seemed odd to me that projects often have hundreds of contributors, and then just 1 copyright holder.
I'd rather see the copyrights just assigned to those who did the work,  plain and simply.

**Comment by calvinmetcalf** [comment]
I didn't say only one copyright holder, I was thinking (c) name and
contributors

**Comment by dcousens** [comment]
@calvinmetcalf works for me,  semantically the same but addresses the issue you raised. :+1: 

@mkillianey are you up to make that change?

**Comment by mkillianey** [comment]
Happy to make the change (and/or have you make the change), whichever's less trouble for you.

I'm not a lawyer, so I don't know if there's a downside to listing "browserify-sign contributors" in the copyright.  For example, if you eventually take this pull request, does that mean that I'm a contributor, and does that confer some rights to me that I really shouldn't have?  Or do we kinda trust that licenses like ISC and MIT make that a moot point?

As for the author/contributors fields in the package.json, I'll uncomplicate the pull request(s) by removing that change from all my browserify pull requests.  For my purposes, I just want to know what text I should use to fairly/correctly acknowledge your wonderful work.

**Comment by calvinmetcalf** [comment]
@mkillianey  I think we want to go with (for this one) `Calvin Metcalf & contributors`

**Pull request merged**
